In [72]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import mglearn

In [73]:
X = np.array([1,3,5,7,6])

In [74]:
# scale numeric data with a scale factor
from logging import error
from pandas import DataFrame, core
def scale(df:core.frame.DataFrame, scaleFactor:int) -> dict:
    if(type(df)!=core.frame.DataFrame):
        return error(msg="Error! variable passed to the 'dataframe' parameter is not a dataframe")
    min = df.min()
    max = df.max()
    df = scaleFactor * (df - min) / (max - min)
    return dict(df=df, min=min, max=max, scaleFactor=scaleFactor)
def scale_inverse(scaleItem:dict) -> core.frame.DataFrame:
    min = scaleItem.get("min")
    max = scaleItem.get("max")
    scaleFactor = scaleItem.get("scaleFactor")
    df = scaleItem.get("df")
    return df*(max-min)/scaleFactor + min


In [75]:
print(X)
display(np.array([X,X+1]))
display(np.transpose(np.array([X,X+1])))

[1 3 5 7 6]


array([[1, 3, 5, 7, 6],
       [2, 4, 6, 8, 7]])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [6, 7]])

In [84]:

from sklearn.utils import shuffle


df = pd.DataFrame(np.transpose([X,X+1]), columns=["row1","row2"])
display(df)
scaleItem = scale(df, 10)
scaleItem2 = scale(shuffle(df), 10)
randoDF = scale_inverse(scaleItem)
display(randoDF)
display(scale_inverse(scaleItem2))


row1  row2
0     1     2
1     3     4
2     5     6
3     7     8
4     6     7

row1  row2
0   1.0   2.0
1   3.0   4.0
2   5.0   6.0
3   7.0   8.0
4   6.0   7.0

row1  row2
3   7.0   8.0
1   3.0   4.0
2   5.0   6.0
0   1.0   2.0
4   6.0   7.0

In [77]:
scaleItem.get("min")

row1    1
row2    2
dtype: int32